dbt_meds:
  target: dev
  outputs:
    dev:
      type: postgres
      host: Postgres_multiple_files
      user: postgres
      password: postgres
      port: 5432
      dbname: data_ingestion
      schema: public
